version: "3"
services:

  jobseeker-app:
    image: jobseeker
    networks:
      - jobseeker-db-network 
    ports:
      - 8080:8080

  postgresql-db:
    image: postgres:9.6
    networks:
      - jobseeker-db-network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=jobseeker
      
networks:
  jobseeker-db-network:
