version: "3"
services:

  jobseeker-app:
    build: .
    container_name: jobseeker-app
    networks:
      - jobseeker-db-network 
    ports:
      - 8080:8080

  postgresql-db:
    image: postgres:9.6
    container_name: postgresql-db
    networks:
      - jobseeker-db-network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=jobseeker
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      
networks:
  jobseeker-db-network:
  
volumes:
    pgdata:
