spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: create
  show-sql: true

spring:
  datasource:
    url: jdbc:postgresql://postgresql-db:5432/jobseeker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver